on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to VPS and Run Commands
      env:
        DEPLOY_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        HOST: 197.140.18.68
        USER: root
      run: |
        sudo apt-get install -y openssh-client
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        
        ssh -o StrictHostKeyChecking=no -i deploy_key $USER@$HOST <<EOF
          # Place your commands here. For example:
          cd /docker-app/deeplyfe_backend
          git pull 
          docker-compose up -d
          # Add any other commands you need
          EOF

